import React from "react";
import { Card, CardBody, CardFooter, Image } from "@nextui-org/react";
import { Link } from "@nextui-org/link";
import DefaultLayout from "@/layouts/default";
import styles from "../styles/hero.module.css";

import {
  Navbar,
  NavbarBrand,
  NavbarContent,
  NavbarItem,
  Button,
} from "@nextui-org/react";

export default function about() {
  return (
    <DefaultLayout>
      <div
        style={{
          backgroundColor: "#D9D9D9",
          width: "80%",
          margin: "40px auto",
        }}
      >
        <h1 style={{ textAlign: "center" }}>
          Privacy Policy for Scoops OF Euphoria
        </h1>
        <p className="hello">Scoops of Euphoria</p>
        <p>123 Maple Street, Newark NJ</p>
        <p>ScoopsEuphoria@gmail.com</p>
        <p>832-734-8946</p>

        <h2>We collect the following types of information:</h2>

        <ul className={styles.myList}>
          <li>
            Basic website usage data via Google Analytics, including page views,
            duration of visit, and referral sources.
          </li>
          <li>
            Personal data provided by you, such as email addresses for
            newsletters or contact forms. This data is used to:
          </li>
        </ul>
        <h1> This data is used to:</h1>
        <ul className={styles.myList}>
          <li>Improve website content and user experience.</li>
          <li>Respond to inquiries or requests.</li>
          <li>Comply with legal obligations.</li>
        </ul>
        <p>
          Our website uses Google Analytics, a web analytics service provided by
          Google, Inc. Google Analytics uses “cookies,” which are text files
          placed on your computer, to help analyze how users use the site. The
          information generated by the cookie about your use of the website will
          be transmitted to and stored by Google.
        </p>
        <h1>Under GDPR, you have various rights including:</h1>
        <ul className={styles.myList}>
          <li>
            Right to access: You can request copies of your personal data.
          </li>
          <li>
            Right to rectification: You can request correction of any incorrect
            or incomplete data.
          </li>
          <li>
            Right to erasure: You can request the deletion of your personal data
            under certain conditions.
          </li>
          <li>
            Right to restrict processing: You can request the restriction of
            processing your personal data.
          </li>
          <li>
            Right to object to processing: You have the right to object to our
            processing of your personal data.
          </li>
          <li>
            Right to data portability: You have the right to request the
            transfer of your data to another organization or directly to you.
          </li>
          <h1 style={{ textAlign: "center" }}>
            By using our website, you hereby consent to our privacy policy and
            agree to its terms.
          </h1>
        </ul>
      </div>
    </DefaultLayout>
  );
}
